### PR TITLE
Fix #309: ORA-00932: inconsistent datatypes: expected - got CLOB

### LINKED ISSUE #309: ORA-00932: inconsistent datatypes: expected - got CLOB
DB queries involving CLOBs are failing in Oracle.

### PR DESCRIPTION
**Pull request by romanstrobl**
Added `@Lob` annotations for JPA mapping of large Strings in Oracle.

### CODE REVIEW

**Review by petrdvorak — APPROVED** [review]
Looks OK

**Review by saalistaja — APPROVED** [review]
Perfect!

**Comment by romanstrobl** [comment]
One more fix, we need to use a large VARCHAR for identification_data and index it for performance reasons.

**Review by saalistaja — APPROVED** [review]
Looks good.

**Pull request merged**
