### PR TITLE
Add initial github action

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by romanstrobl — CHANGES_REQUESTED** [review]
Can we synchronize this with https://github.com/wultra/powerauth-crypto/pull/414/files ?

**Comment by banterCZ** [comment]
I have renamed the file and add `workflow_dispatch`. I am not sure about publish. May we postpone it to another PR?

**Comment by romanstrobl** [comment]
We will probably create a reusable workflow we can use across all PowerAuth backends, so let's postpone this pull request until this is ready.

**Comment by romanstrobl** [comment]
See: https://github.com/wultra/lime-java-core/pull/116/files

**Review by romanstrobl — APPROVED** [review]
I am satisfied with the changes now.

**Pull request merged**
