### PR TITLE
Fix #227: Setup Compiler for Java 11 LTS

### LINKED ISSUE #227: Setup Compiler for Java 11 LTS
Setup Compiler for Java 11 LTS. In pom.xml, there is confusing mixture of 8 and 9.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

**Review by romanstrobl — APPROVED** [review]
Yes, we can use Java 11 (which is an LTS version) as a minimum supported version. We should probably reflect this change in documentation.

**Comment by banterCZ** [comment]
> Yes, we can use Java 11 (which is an LTS version) as a minimum supported version. We should probably reflect this change in documentation.

In Deploying-Enrollment-Server.md there is:
> ## Supported Java Runtime Versions
> 
> The following Java runtime versions are supported:
> - Java 11 (LTS release)
> - Java 17 (LTS release)

**Comment by romanstrobl** [comment]
Ah ok, then it is fine.

**Comment by saalistaja** [comment]
Thus can we then rollback all the nice merged changes from https://github.com/wultra/enrollment-server/pull/209 ?

**Comment by banterCZ** [comment]
> Thus can we then rollback all the nice merged changes from #209 ?

#209 has never been merged, see https://github.com/wultra/enrollment-server/pull/209#issuecomment-1156159362

**Comment by saalistaja** [comment]
> > Thus can we then rollback all the nice merged changes from #209 ?
> 
> #209 has never been merged, see [#209 (comment)](https://github.com/wultra/enrollment-server/pull/209#issuecomment-1156159362)

Thanks God! :)

**Pull request merged**
